# version: "3.3"
services:
  apache:
    container_name: php-${PHP_VERSION}
    build:
      context: .
      dockerfile: ${PHP_IMAGE}
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
    links:
      - db
    networks:
      - mydev
    volumes:
      - type: bind
        source: ./html
        target: /var/www/html
        consistency: delegated
      # Enable the next line if you want to add a custom php.ini
      - ./php.ini:/usr/local/etc/php/conf.d/999-customphp.ini
    environment:
      SMTP_HOST: mailhog
      SMTP_PORT: 1025

  db:
    image: mysql
    expose:
      - 3306
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/mysql
        consistency: delegated
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: mydev
      MYSQL_PASSWORD: root
      MYSQL_COLLATION: utf8mb4_unicode_ci
    networks:
      - mydev

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - mydev

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Web UI port
    networks:
      - mydev
    environment:
      MH_UI_BIND_ADDR: 0.0.0.0:8025

volumes:
  dbdata:

networks:
  mydev:
    driver: bridge
