version: '3.9'
services:
  apache74:
    build: 
      context: .
      dockerfile: ./php/Dockerfile.apache74
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mysql
    links:
      - mysql
    networks:
      - mydev
    volumes:
      - type: bind
        source: ./html
        target: /var/www/html
        consistency: delegated
      # - ~/.composer/auth.json:/root/.composer/auth.json
      # Enable the next line if you want to add a custom php.ini
      - ./php.ini:/usr/local/etc/php/conf.d/999-customphp.ini

  mysql:
    image: mysql
    restart: always
    expose:
     - 3306
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/mysql
        consistency: delegated
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: mydev
      MYSQL_PASSWORD: root
      MYSQL_COLLATION: utf8mb4_unicode_ci
    networks:
      - mydev
    
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    networks:
      - mydev

volumes:
  dbdata:

networks:
  mydev:
    driver: bridge
